### ISSUE TITLE
Any software including this should have a copyright license

### ISSUE THREAD

**Issue by DiogoConstantino** [Data-Protection-Control/browser-extension#1]
Any software including this should have a copyright license, if not users rights are necessarily limited by what the law allows (very little and very different from country to country), and contributions are less likely to appear, because contributors are likely to be confused about what's to be expected regarding copyright.

**Comment by gb-noyb** [comment]
Thanks for reminding us. I just slapped an MIT licence on it, assuming that would generally work for people. Closing this, but feel free to reopen if you have further comments.
